version: '3.4'
services:

  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
    depends_on:
      - kafka
      - postgres

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"

  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - persistence:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  persistence:
    name: persistence