version: '3'
services:

  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    restart: always
    depends_on:
      - kafka

  zookeeper:
    image: confluent/zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
