version: '3.4'
services:

  app:
    build: .
    ports:
      - "8001:5001"
    env_file: .env
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - persistence:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  persistence:
