"""empty message

Revision ID: 13d6ed0804f6
Revises: 5c24b1e405bf
Create Date: 2019-05-17 08:14:18.103110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d6ed0804f6'
down_revision = '5c24b1e405bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('mb_id', sa.Text(), nullable=True))
    op.add_column('tracks', sa.Column('mb_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'mb_id')
    op.drop_column('albums', 'mb_id')
    # ### end Alembic commands ###
