"""empty message

Revision ID: 2b832e34c051
Revises: d1db2d69313e
Create Date: 2019-06-10 18:09:17.399434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b832e34c051'
down_revision = 'd1db2d69313e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections', sa.Column('artists_raw', sa.Text(), nullable=True))
    op.add_column('sections', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('sections', sa.Column('type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections', 'type')
    op.drop_column('sections', 'number')
    op.drop_column('sections', 'artists_raw')
    # ### end Alembic commands ###
