"""empty message

Revision ID: 30481feeb7b9
Revises: 6b61c84b63c8
Create Date: 2019-05-24 22:59:34.294687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '30481feeb7b9'
down_revision = '6b61c84b63c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('img', sa.Text(), nullable=True))
    op.add_column('albums', sa.Column('thumb', sa.Text(), nullable=True))
    op.drop_column('albums', 'images_json')
    op.add_column('artists', sa.Column('img', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('thumb', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'thumb')
    op.drop_column('artists', 'img')
    op.add_column('albums', sa.Column('images_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('albums', 'thumb')
    op.drop_column('albums', 'img')
    # ### end Alembic commands ###
