"""empty message

Revision ID: 5f579251964b
Revises: c45f3a91e227
Create Date: 2019-05-24 12:22:29.229432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f579251964b'
down_revision = 'c45f3a91e227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('dbp_uri', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_timestamp'), 'locations', ['timestamp'], unique=False)
    op.add_column('artists', sa.Column('birthplace_id', sa.Integer(), nullable=True))
    op.add_column('artists', sa.Column('hometown_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'locations', ['hometown_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'artists', 'locations', ['birthplace_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'hometown_id')
    op.drop_column('artists', 'birthplace_id')
    op.drop_index(op.f('ix_locations_timestamp'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
