"""empty message

Revision ID: 6b61c84b63c8
Revises: 5f579251964b
Create Date: 2019-05-24 13:35:18.058316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b61c84b63c8'
down_revision = '5f579251964b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_birthplace',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'artist_id')
    )
    op.create_table('artist_hometown',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'artist_id')
    )
    op.drop_constraint('artists_birthplace_id_fkey', 'artists', type_='foreignkey')
    op.drop_constraint('artists_hometown_id_fkey', 'artists', type_='foreignkey')
    op.drop_column('artists', 'birthplace_id')
    op.drop_column('artists', 'hometown_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('hometown_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('birthplace_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('artists_hometown_id_fkey', 'artists', 'locations', ['hometown_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('artists_birthplace_id_fkey', 'artists', 'locations', ['birthplace_id'], ['id'], ondelete='CASCADE')
    op.drop_table('artist_hometown')
    op.drop_table('artist_birthplace')
    # ### end Alembic commands ###
