"""empty message

Revision ID: 7b199ba57d25
Revises: f11ee6f512b4
Create Date: 2019-09-06 07:56:47.777506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b199ba57d25'
down_revision = 'f11ee6f512b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('wikipedia_uri', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('wikipedia_uri', sa.Text(), nullable=True))
    op.add_column('genres', sa.Column('wikipedia_uri', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('wikipedia_uri', sa.Text(), nullable=True))
    op.alter_column('sections', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tracks', sa.Column('wikipedia_uri', sa.Text(), nullable=True))
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracks', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tracks', 'wikipedia_uri')
    op.alter_column('sections', 'track_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('locations', 'wikipedia_uri')
    op.drop_column('genres', 'wikipedia_uri')
    op.drop_column('artists', 'wikipedia_uri')
    op.drop_column('albums', 'wikipedia_uri')
    # ### end Alembic commands ###
