"""empty message

Revision ID: 92016ded09fe
Revises: 0ab3831208d2
Create Date: 2019-12-05 19:28:56.194718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92016ded09fe'
down_revision = '0ab3831208d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Songs', ['id'])
    op.create_index(op.f('ix_albums_release_date'), 'albums', ['release_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_albums_release_date'), table_name='albums')
    op.drop_constraint(None, 'Songs', type_='unique')
    # ### end Alembic commands ###
