"""empty message

Revision ID: c45f3a91e227
Revises: b37b63eca3ed
Create Date: 2019-05-23 09:59:11.234535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c45f3a91e227'
down_revision = 'b37b63eca3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('mb_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tracks', sa.Column('mb_obj', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'mb_obj')
    op.drop_column('albums', 'mb_obj')
    # ### end Alembic commands ###
